### ISSUE TITLE
Doesn't work with symbols

### ISSUE THREAD

**Issue by fgarduno** [DWilliames/Google-sheets-content-sync-sketch-plugin#1]
How to use this plugins with a symbol design?

**Comment by DWilliames** [comment]
Thanks @fgarduno. Yes, unfortunately it currently doesn't work with Symbols. I am hoping to add this feature — it involves a fair bit more work to make it work with Symbols. Bare with me as I find time to make this fix. Thanks for your patience.

**Comment by DWilliames** [comment]
@fgarduno — I have now made it work with symbols. Check https://github.com/DWilliames/Google-sheets-content-sync-sketch-plugin#working-with-symbols for a bit of an explanation.
Unfortunately it doesn't support nested symbols at this stage. Let me know how you go!!

**Comment by fgarduno** [comment]
Thank you!!!!
