### ISSUE TITLE
Update Sketch with Image URLs

### ISSUE THREAD

**Issue by axertion** [DWilliames/Google-sheets-content-sync-sketch-plugin#10]
Feature Request:
Would it be possible to add the ability to update the sketch file with image URLs pasted into the Google Spreadsheet?

For example, I have a grid of people like this:
![image](https://user-images.githubusercontent.com/617549/31516431-237e31a4-af5e-11e7-81f6-9ea75c76fe7e.png)

Ideally, I'd like to add an avatar image for each of them in the Google Spreadsheet, like this:
![image](https://user-images.githubusercontent.com/617549/31516509-6947337a-af5e-11e7-8a18-b479ebb58a50.png)

Would this be possible to add to this Sketch plugin?

**Comment by DWilliames** [comment]
Sorry for the delay. This is a fantastic idea! 
I will definitely look into doing this.

**Comment by msawmiller** [comment]
Definitely a great idea here.

**Comment by DWilliames** [comment]
This should work now!!

**Comment by clarklab** [comment]
Does this feature still work? I've got text filling fine but images don't seem to work...
