### ISSUE TITLE
Impossible run the plugin

### ISSUE THREAD

**Issue by MattCowBoy** [DWilliames/Google-sheets-content-sync-sketch-plugin#2]
Hi, I'm very interested in using this plugin to improve my workflow with copywriters.
I tried to install and run your plugin but seems it doesn't work. I can't run the plugin. Using the sketch debbuger (runScript command) I saw that there is a "Syntax error" in the first foreach.

I have the last version of Sketch.
Can you let me know if you have the same problem?
Thank you

**Comment by DWilliames** [comment]
Thanks @MattCowBoy — I think I may know what caused this. I have made a fix under the develop branch; can you please verify if this has fixed the issue.
You can download the update from: https://github.com/DWilliames/Google-sheets-content-sync-sketch-plugin/archive/develop.zip

**Comment by MattCowBoy** [comment]
Hi, now I can run the plugin but when I insert the URL of my Google sheet nothing happens.
I try to debug it and I receive an error in the main.js file, " Can't find variable: getJSONFromFile
line: 17".

Can you please verify this?
Thank you very much

**Comment by DWilliames** [comment]
Thanks @MattCowBoy. Can you try https://github.com/DWilliames/Google-sheets-content-sync-sketch-plugin/archive/develop.zip now and see if it is fixed now?

If its not fixed, are you able to provide the publish link to the Google Sheets doc you are using?

Cheers.

**Comment by MattCowBoy** [comment]
Yes, it works perfectly, thank you. 
Is it possible to import rich text into Sketch?
I'd like content to be transferred from Google Sheet including style (e.g. bold, underline and italic). I'm not interested in importing font size. I think a plugin like this would be awesome for responsive projects where content is almost the same on each device, but with different font size.

Let me know and thank you so much @DWilliames 
Cheers

**Comment by DWilliames** [comment]
Awesome. Glad I could fix the problem.

Unfortunately its not possible to import rich text from Google Sheets. Maybe it would be possible through some other service — but Google Sheets currently only returns the text; no formatting.

I'll look into other possibilities though. :) 
Cheers.
