### ISSUE TITLE
Google sheet plugin not working

### ISSUE THREAD

**Issue by vincentag** [DWilliames/Google-sheets-content-sync-sketch-plugin#30]
# I'm using the latest Sketch version (53.2)

1. copy the google sheet link
2. paste it in Sketch
3. got this error

<img width="537" alt="Screen Shot 2019-03-29 at 4 40 44 PM" src="https://user-images.githubusercontent.com/29769714/55240360-6e655f80-5241-11e9-9da8-a91119afa1b8.png">

**Comment by julienpecorino** [comment]
Thanks for creating this plugin this exactly what I was looking for.
I see the same error in my side, I can't connect to the published spreadsheet, I'm using the correct url, I did try 30 times.

Would be great if you could fix it!
Thanks
