### ISSUE TITLE
Can't sync different sheets

### ISSUE THREAD

**Issue by chuca** [DWilliames/Google-sheets-content-sync-sketch-plugin#4]
Hello!
Thank you very much for create this amazing plugin!
I'm using it with a single sheet and it works perfectly, but if a use another sheet (for another artwork) I get an N/A: https://cl.ly/ljV6
And if I use the same #layertitle (for example) in both pages I get the same content of the first sheet.

I'm using v1.1.1 btw

Thanks again!

**Comment by DWilliames** [comment]
Hey @chuca, sorry about that. Are you able to provide the Sketch file and/or the Google Sheets link so I can have a bit more context to work with. Not too sure why it isn't working full for you :/

**Comment by DWilliames** [comment]
Hey @chuca. This issue has been opened for a while without a response. 
Are you able to provide more detail for me to try and help solve it? Otherwise I will close this issue if I don't get a response in the next couple of days.
