### ISSUE TITLE
Import not working - possible url issue

### ISSUE THREAD

**Issue by Toinman** [DWilliames/Google-sheets-content-sync-sketch-plugin#6]
This plugin doesn't work. Import is never working. 

My public sheet is:
https://docs.google.com/spreadsheets/d/e/2PACX-1vTfVYwW-wb3CRaP9Z2ageQMRo-u6CPXxBex7xWTRhQ-o2lBrMjyC_JdFECgyh7SRu9by_-yHecJ82M7/pubhtml

Another issue explains the url cannot contain "/d/e" but this is how Google generates the url. I tried different settings, but "/d/e" is always in the url.

**Comment by DWilliames** [comment]
Thanks @Toinman. I need to update the Plugin to give a contextual alert on how to fix this. 
It appears that now the URL that is generated within the 'Publish to the Web' page does not work. But after you have 'published' it — use the URL in the browser address bar instead and it should work.

To recap...
Don't use this URL.
![unnamed](https://user-images.githubusercontent.com/6570446/29693505-5f5dd19e-8979-11e7-8e99-96604a3dfdca.png)

Instead, use the URL in the address bar
![unnamed-1](https://user-images.githubusercontent.com/6570446/29693510-6736f13e-8979-11e7-8558-3d85396e5f0b.png)

**Comment by Toinman** [comment]
Thank you! This works! 

(note to avoid confusing for others, it is still necessary to 'publish to the web', you should just use the different url)

**Comment by DWilliames** [comment]
Thanks again @Toinman. I have now updated the plugin to do some more URL validation and make this clearer to users.
